
spring:
 application:
  name: Inventory Loader Service
 data:    mongodb:      database: inventory_management
  
    
server:
 port: 9090
 
    
management:
  endpoints:
    web:
      exposure:
        include: "*"
        
info:
  app:
   name: Inventory Loader Service
   description: Inventory Loader application is used to get Products from inventory
   version: 1.0.0        
        